### ISSUE TITLE
Webstorm

### ISSUE THREAD

**Issue by Agamennon** [zewa666/aurelia-node#3]
Thanks for this, i was wondering if you could build a starter project for Webstorm + node(since it can do es6 without Babel (it uses traceur) has support for protractor and karma, so this could also be inserted in, i write this mostly because i can't seem to get things to work on this configuration, it seems that a lot is going on on gulp, and i don't understand that frankly, many will use Webstorm to work on aurelia and to set up a aurelia work flow on webstorm is showing not to be trivial, if you have any tips i would also appreciate

**Comment by zewa666** [comment]
Hi there,

I'm not sure I fully follow what you would like to have. I've just recently started using WebStorm so might I miss some things.
1. Webstorm + Node without Babel
   The example provided here uses classic ES5 in Node no use of Babel at all.
   Babel is used for Aurelia itself.
2. Protractor
   Not sure there is a special feature provided here. What I've seen is that you can create your custom run configuration (Node.js app -> protractor + protractor.conf)
3. Karma
   This works for me by simply rightclicking the karma.conf file and executing it inside WebStorm.
4. Gulp
   The recent version has Gulp support. Just rightclick the gulpfile and click "Show Gulp Tasks" in there just use the Watch task. thats it.
5. Traceuer vs Babel
   I don't quite get yet why you'd want to exchange it, but there for sure is a way to set it up with custom Watchers in WebStorm. Nevertheless all of this is not needed as long as you keep the Gulp Watch task running.

---

So essentially I do not see what I should provide here since for me kinda everything works. Could you elaborate your problems a bit more in detail?
